cask_args appdir: '/Applications'

# tap 'homebrew/brew'

brew 'atuin'
brew 'cloudflared'
brew 'gh'
brew 'imagemagick'
brew 'postgresql@17'
brew 'protobuf'
brew 'redis'
brew 'ruby-build'
brew 'spaceman-diff'
brew 'spark'
brew 'temporal'
brew 'wget'
brew 'yt-dlp'

# cask 'vlc'
# cask '1password'
# cask 'airtable'
# cask 'arq'
# cask 'diffusionbee'
# cask 'ghostty'
# cask 'handbrake-app'
# cask 'messenger'
# cask 'notion-calendar'
# cask 'plex'
# cask 'qlvideo'
# cask 'sonos'
# cask 'steam'
# cask 'transmission'
# cask 'raycast'
# cask 'whatsapp'
# cask 'windsurf'
# cask 'visual-studio-code'
# cask 'zed'
# cask 'zoom'
